name: songjog
publish_to: 'none'
description: Songjog — owner-first business, service, education and institution management.
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  package_info_plus: ^10.2.1
  device_info_plus: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
